server:
  port: 9090
  servlet:
    context-path: /bs

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bs?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapperLocations: classpath:mapper/*.xml